### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by yaelahan** [ferixio/kpri#1]
**MEMBER/CLIENT**

- [ ] Permohonan Pinjaman Uang
- [ ] Permohonan Kredit Barang
- [ ] Permohonan Kredit Mobil
- [ ] Cetak Surat Permohonan
---
- [ ] Order Barang Toko
- [ ] Order Sewa mobil
- [ ] Order Jasa Bengkel
---
- [ ] Menu Pengaturan
- [ ] Menu dashboard ( berita dan daftar permohonan )
- [ ] Menu daftar permohonan
- [ ] Menu chating
- [ ] Menu Notifikasi 
- [ ] Menu Informasi koperasi
- [ ] Menu Informasi simpanan dan tabungan
- [ ] Menu rubah Password

**ADMIN**
- [ ] Meresponse Permohonan Pinjaman Uang
- [ ] Meresponse Permohonan kredit barang
- [ ] Meresponse Permohonan Kredit Mobil
- [ ] Muncul Notifikasi dari Permohonan Customer 
---
- [ ] Meresponse Order Barang Toko
- [ ] Meresponse Order Sewa mobil
- [ ] Meresponse  Order Jasa Bengkel
---
- [ ] Menu Pengaturan
- [ ] Menu dashboard ( grafik )
- [ ] Menu daftar permohonan
- [ ] Menu chating
- [ ] Menu Notifikasi 
- [ ] Menu rubah Password
